version: '3'

services:
  main:
    build: ./main
    depends_on:
      - dind
      - redis
    ports:
      - 10559:5000
      - 10560:8888
    environment:
      - DOCKER_HOST=tcp://dind:2375
    volumes:
      - ./main:/root/main
      - ./trainings:/root/main/trainings
      - ./config.json:/root/main/config.json
      # - ./tmp:/root/main/tmp

  dind:
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    volumes:
      - ./daemon.json:/etc/docker/daemon.json
      - ./trainings:/root/main/trainings
      # - ./tmp:/root/main/tmp

  redis:
    image: redis
