version: '3'

services:
  mian:
    build: ./main
    # image: python:3.8
    tty: true
    depends_on:
      - dind
      - redis
    ports:
      - 10559:5000
    volumes:
      - ./tmp:/run
      - ./main:/root/main
      - ./trainings:/root/main/trainings
      - ./config.json:/root/main/config.json


  dind:
    image: docker:dind
    privileged: true
    volumes:
      - ./tmp:/run

  redis:
    image: redis
